### ISSUE TITLE
unknown base type

### ISSUE THREAD

**Issue by sei-jgwohlbier** [epiqsolutions/gr-sidekiq#19]
Trying to run in gnuradio 3.10.1.1

```
Traceback (most recent call last):
  File "/home/gnuradio-user/work/gnuradio-flowgraphs/sidekiq/sidekiq_rx.py", line 34, in <module>
    from gnuradio import sidekiq
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/sidekiq/__init__.py", line 18, in <module>
    from .sidekiq_python import *
ImportError: generic_type: type "sidekiq_tx" referenced unknown base type "gr::sync_block"

>>> Done (return code 1)
```

**Comment by sei-jgwohlbier** [comment]
I was building with `clang-17`. Changing to `gcc-11.4.0` fixed the problem.
